name: Publish Docker Image
on: push
jobs:
  push_to_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nomadnmr/server

      - name: Echo metadata
        run: |
          echo "${{steps.meta.outputs.tags}}"
          echo "${{steps.meta.outputs.labels}}"
