name: Deploy API
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: nomad-server/nomad-rest-api
          path: nomad-rest-api
      - name: Install dependencies
        working-directory: nomad-rest-api
        run: npm ci
      - name: Test
        working-directory: nomad-rest-api
        run: npm test
