name: Deploy API
on: push
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: nomad-rest-api
        run: npm ci
      - name: Test
        working-directory: nomad-rest-api
        run: npm run test-action
